#!/usr/bin/env bash
# It does the following:
#   It creates a file /var/run/myscript.pid containing the script PID.
#   It displays "To infinity and beyond" indefinitely
#   It displays "I hate the kill command" upon receiving a SIGTERM
#   It displays "Y U no love me?!" upon receiving a SIGINT
#   It deletes the file /var/run/myscript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done

