#!/usr/bin/env bash
# This displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

countz=0

while [ $countz -lt 10 ]
do
  if [ $countz -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( countz++ ))
done
